### ISSUE TITLE
Site-wide search & search section

### ISSUE THREAD

**Issue by ciphrd** [fxhash/fxhash-website#395]
* base branch: `dev`
* requires #389 to avoid debt down the line

We want to add a site-wide search to facilitate exploring the content on the platform.

You will find the design for this section here (it's pretty self-explanatory): https://www.figma.com/file/bdCVYIEKTy8lyBLjIDWvQn/Website?node-id=38%3A823

The search section will be located under `/search`.
Every section will have its url:
* `/search/users`
* `/search/generative`
* `/search/articles`
* `/search/marketplace`

The search section will accept 1 query parameter `query` which is the query string, url encoded. Each sub section also supports this query parameter.

ex: `/search?query=this%20is%20a%20search` or `/search/users?query=this%20is%20a%20search`

The search bar is filled with the search query when the page is loaded. We do not refresh the search on key stroke but only when the user presses enter.

The button `explore more` on the summary points to the corresponding sub tab.
The button `see more results` displays more results by running a query in the appropriate section.

# GraphQL

Here is a quickly crafted query to run a site-wide search against the graphql api:

query
```graphql
query Search(
  $filters: UserFilter,
  $sort: UserSortInput,
  $generativeTokensFilters2: GenerativeTokenFilter,
  $generativeTokensSort2: GenerativeSortInput, 
  $articlesFilters2: ArticleFilter, 
  $articlesSort2: ArticleSortInput, 
  $listingsFilters2: ListingFilter, 
  $listingsSort2: ListingsSortInput
) {
  users(filters: $filters, sort: $sort) {
    id
    name
  }
  generativeTokens(filters: $generativeTokensFilters2, sort: $generativeTokensSort2) {
    id
    name
  }
  articles(filters: $articlesFilters2, sort: $articlesSort2) {
    id
    title
  }
  listings(filters: $listingsFilters2, sort: $listingsSort2) {
    id
    objkt {
      id
      name
    }
    price
  }
}
```

variables
```json
{
  "filters": {
    "searchQuery_eq": "test",
    "flag_in": ["NONE", "VERIFIED"]
  },
  "sort": {
    "relevance": "DESC"
  },
  "generativeTokensFilters2": {
    "searchQuery_eq": "test",
    "flag_in": [
      "NONE",
      "CLEAN"
    ]
  },
  "generativeTokensSort2": {
    "relevance": "DESC"
  },
  "articlesFilters2": {
    "searchQuery_eq": "test",
    "flag_in": ["NONE", "CLEAN"]
  },
  "articlesSort2": {
    "relevance": "DESC"
  },
  "listingsFilters2": {
    "searchQuery_eq": "test"
  },
  "listingsSort2": {
    "relevance": "DESC"
  }
}
```

# TODO

- [x] search bar at the top of the website (handle responsive properly)
- [x] search is linked to the url parameter `query`, and is set when triggering a search
- [x] search summary
- [x] see more results for every section
- [x] custom tab for every section (same implementation as their equivalent on the rest of the website)
